export const projects = [
    {
        id: 1,
        title: "Cali-Cafe Site",
        coverImg: "",
        description1: "",
        techStack: "",
        deployedLink: "",
        githubLink: "",
    },
    {
        id: 2,
        title: "User-Account Fullstack",
        coverImg: "",
        description1: "",
        techStack: "",
        deployedLink: "",
        githubLink: "",
    },
    {
        id: 3,
        title: "Coderheroes E-Learning",
        coverImg: "",
        description1: "",
        techStack: "",
        deployedLink: "",
        githubLink: "",
    },
    {
        id: 4,
        title: "",
        coverImg: "",
        description1: "",
        techStack: "",
        deployedLink: "",
        githubLink: "",
    },
    {
        id: 5,
        title: "Ecommerce Fullstack",
        coverImg: "",
        description1: "",
        techStack: "",
        deployedLink: "",
        githubLink: "",
    },
]